// R41: MSW browser worker for dev-mode opt-in
// (`VITE_MOCKS=1 pnpm dev`).
//
// `setupWorker` registers the handlers against the service worker
// installed at `public/mockServiceWorker.js` (generated by
// `pnpm exec msw init public/`). The worker only loads in dev mode
// via the dynamic import in `main.tsx` — it is not part of the
// production bundle.

import { setupWorker } from 'msw/browser';

import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
