"""baseline — reproduce mainstream's current schema (R78).

Reproduces the 4 tables (workspaces, datasets, queries incl. R76
`source_id`, relationships) with their columns, types, FK + ON DELETE
CASCADE, CHECK constraints, and the R25/R69/R70 indexes — i.e. exactly
the schema the retired hand-bootstrapped `_SCHEMA` built. Autogenerated
from `app.db_models` (the schema of record) and reviewed; future schema
changes are NEW revisions, never edits to this baseline. Parity with the
models is pinned by `tests/test_schema_parity.py`.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-16
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('length(name) BETWEEN 1 AND 80'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index('idx_workspaces_name_unique', ['name'], unique=True)

    op.create_table('datasets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('columns_json', sa.Text(), nullable=False),
    sa.Column('source_format', sa.Text(), nullable=False),
    sa.Column('sheet_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("source_format IN ('csv', 'excel')"),
    sa.CheckConstraint('column_count >= 1'),
    sa.CheckConstraint('length(name) BETWEEN 1 AND 120'),
    sa.CheckConstraint('row_count >= 0'),
    sa.CheckConstraint('size_bytes >= 0'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index('idx_datasets_name_unique', ['workspace_id', 'name'], unique=True)
        batch_op.create_index('idx_datasets_workspace_id', ['workspace_id'], unique=False)

    op.create_table('queries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('definition_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('length(name) BETWEEN 1 AND 120'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.create_index('idx_queries_dataset_id', ['dataset_id'], unique=False)
        batch_op.create_index('idx_queries_name_unique', ['workspace_id', 'name'], unique=True)
        batch_op.create_index('idx_queries_workspace_id', ['workspace_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('left_dataset_id', sa.Text(), nullable=False),
    sa.Column('left_column', sa.Text(), nullable=False),
    sa.Column('right_dataset_id', sa.Text(), nullable=False),
    sa.Column('right_column', sa.Text(), nullable=False),
    sa.Column('cardinality', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("cardinality IN ('one_to_one', 'one_to_many', 'many_to_many')"),
    sa.ForeignKeyConstraint(['left_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index('idx_relationships_pair_unique', ['workspace_id', 'left_dataset_id', 'left_column', 'right_dataset_id', 'right_column'], unique=True)
        batch_op.create_index('idx_relationships_workspace_id', ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index('idx_relationships_workspace_id')
        batch_op.drop_index('idx_relationships_pair_unique')

    op.drop_table('relationships')
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index('idx_queries_workspace_id')
        batch_op.drop_index('idx_queries_name_unique')
        batch_op.drop_index('idx_queries_dataset_id')

    op.drop_table('queries')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index('idx_datasets_workspace_id')
        batch_op.drop_index('idx_datasets_name_unique')

    op.drop_table('datasets')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index('idx_workspaces_name_unique')

    op.drop_table('workspaces')
    # ### end Alembic commands ###
